### PR TITLE
Incorporate da70 changes

### PR DESCRIPTION
**Pull request by jgpawletko**
Incorporate changes requested by David Arjanik.
Bump version to v7.0.0 as elements in v6 are no longer called out in the model.

### CODE REVIEW

**Comment by da70** [comment]
@jgpawletko, looks great.  There is one change I could suggest: if the note about `<emph>` and `<lb>` in mixed content is made using a general comment at the top as opposed to in the note fields of the individual elements, then I would list the exceptions for `<lb>` processing in its note.  Currently, `<lb>` is not converted to `<br>` in `<title>` or `<titleproper>`.

**Comment by jgpawletko** [comment]
> . Currently, is not converted to
> in <title> or .

Hi @da70 , 
Thank you for your comment.  Could you please elaborate on the portion of the comment quoted above?
I don't understand, and I'm wondering if some markup was munched by GitHub when you posted the comment.
Thanks!

**Comment by da70** [comment]
@jgpawletko, sorry, I've backticked the tags and the comment is readable now.

**Comment by jgpawletko** [comment]
> @jgpawletko, sorry, I've backticked the tags and the comment is readable now.

Thank you, @da70 !

**Comment by jgpawletko** [comment]
Hi @da70 , 
I incorporated the change re: `<lb>` that you suggested.

Hi @da70 , @lhenze ,
Please let me know if it's OK to merge this PR.

Thanks!
Best-
Joe

**Comment by da70** [comment]
@jgpawletko: PR looks good to me.

**Pull request merged**
